server:
  port: 8812
  servlet:
    context-path: /bus-client2

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,env
spring:
  rabbitmq:
    port: 5672
    virtual-host: /
    host: 192.168.111.134
    username: admin
    password: admin





