server:
  port: 8802
  servlet:
    context-path: /hystrix
spring:
  application:
    name: springcloud-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/  #,http://localhost:8762/eureka/
    #连接到Eureka服务器所需的等待时间（秒）
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 8
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
    #设置所有实例的默认值(默认是THREAD线程池隔离)
      execution:
        isolation:
          strategy: THREAD
          thread:
            #用来设置thread和semaphore两种隔离策略的超时时间，默认值是1000
            timeoutInMilliseconds: 1000

