server:
  port: 8801
spring:
  application:
    name: springcloud-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
    eureka-server-connect-timeout-seconds: 5

