server:
  port: 8818
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          #服务名小写,如果开启了lowerCaseServiceId,则只能用小写,不能识别大写,如果不开启,只能识别大写
          lower-case-service-id: true

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always








