server:
  port: 8800
  servlet:
    context-path: /ribbon
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
spring:
  application:
    name: springcloud-ribbon
#数据源
  datasource:
    url: jdbc:h2:mem:test
    data: classpath:db/data-h2.sql
    schema: classpath:db/schema-h2.sql
    driver-class-name: org.h2.Driver
    username: root
    password: test
#针对单个服务的 Ribbon 配置
SPRINGCLOUD-PRODUCER-H2DATABASE:
  ribbon:
    ## 基于配置文件形式的 针对单个服务的 Ribbon 负载均衡策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    ##超时重试机制
    ##Spring Cloud 整合了Spring Retry 来增强RestTemplate的重试能力，当一次服务调用失败后，不会立即抛出一次，而是再次重试另一个服务
    ConnectTimeout: 250 # Ribbon的连接超时时间
    ReadTimeout: 1000 # Ribbon的数据读取超时时间
    OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
    MaxAutoRetries: 1 # 对当前实例的重试次数
